Revert "gradle++"
This reverts commit 55e6ae56aa9e76338f52652a34a7e840e9007ec2.

this breaks upnp java.lang.NoClassDefFoundError: javax/servlet/http/HttpServlet